### ISSUE TITLE
1.3.3 镜像 up 之后提示访问，提示 window is not defined

### ISSUE THREAD

**Issue by DeepenLau** [easy-mock/easy-mock-docker#3]
![image](https://user-images.githubusercontent.com/14030995/33419605-1ca74218-d5e6-11e7-9e58-31eec5acacc3.png)

```bash
07:42:32.252Z ERROR easy-mock: error during render : / (req_id=726b8f10-76c9-402d-a88c-8842e1aa0fc2)
web_1      | 07:42:32.252Z ERROR easy-mock: (req_id=726b8f10-76c9-402d-a88c-8842e1aa0fc2)
web_1      |     ReferenceError: window is not defined
web_1      |         at exports.default (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:8471:5)
web_1      |         at Object.defineProperty.value (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:8455:20)
web_1      |         at __webpack_require__ (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:30:30)
web_1      |         at Object.<anonymous> (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:3669:13)
web_1      |         at __webpack_require__ (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:30:30)
web_1      |         at Object.module.exports.version (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:536:15)
web_1      |         at __webpack_require__ (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:30:30)
web_1      |         at Object.<anonymous> (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:6981:15)
web_1      |         at __webpack_require__ (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:30:30)
web_1      |         at Object.<anonymous> (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:1693:3)
web_1      |         at __webpack_require__ (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:30:30)
web_1      |         at Object.defineProperty.value (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:6799:15)
web_1      |         at __webpack_require__ (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:30:30)
web_1      |         at Object.defineProperty.value (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:6776:3)
web_1      |         at __webpack_require__ (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:30:30)
web_1      |         at Object.<anonymous> (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:6762:21)
web_1      |         at __webpack_require__ (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:30:30)
web_1      |         at Object.<anonymous> (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:5423:21)
web_1      |         at __webpack_require__ (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:30:30)
web_1      |         at module.exports.rawScriptExports (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:73:18)
web_1      |         at /home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:76:10
web_1      |         at webpackUniversalModuleDefinition (/home/easy-mock/easy-mock/node_modules/iview/dist/iview.js:3:20)
web_1      | 07:42:32.253Z ERROR easy-mock:   --> GET / 500 6ms (req_id=726b8f10-76c9-402d-a88c-8842e1aa0fc2, duration=6, req.remoteAddress=::ffff:172.25.0.1, req.remotePort=40552)
```

1.3.0 的时候正常

**Comment by DuanPengfei** [comment]
是 iview 的 bug 导致的，iview 已经升级修复了，easymock 刚刚也升级了，可以使用 1.3.6 版本的 Docker 镜像了。

**Comment by DeepenLau** [comment]
好的，1.3.6测试正常

**Comment by DuanPengfei** [comment]
👌 那 issue 就关闭了。
